# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculos.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphsWindow(object):
    def setupUi(self, GraphsWindow):
        GraphsWindow.setObjectName("GraphsWindow")
        GraphsWindow.resize(657, 574)
        self.centralwidget = QtWidgets.QWidget(GraphsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_get_graphs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_graphs.setGeometry(QtCore.QRect(480, 480, 111, 23))
        self.pushButton_get_graphs.setObjectName("pushButton_get_graphs")
        GraphsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GraphsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 21))
        self.menubar.setObjectName("menubar")
        GraphsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GraphsWindow)
        self.statusbar.setObjectName("statusbar")
        GraphsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GraphsWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphsWindow)

    def retranslateUi(self, GraphsWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphsWindow.setWindowTitle(_translate("GraphsWindow", "GraphsWindow"))
        self.pushButton_get_graphs.setText(_translate("GraphsWindow", "Obtener Imagenes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphsWindow = QtWidgets.QMainWindow()
    ui = Ui_GraphsWindow()
    ui.setupUi(GraphsWindow)
    GraphsWindow.show()
    sys.exit(app.exec_())
