# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_visualization.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphsWindow(object):
    def setupUi(self, GraphsWindow):
        GraphsWindow.setObjectName("GraphsWindow")
        GraphsWindow.resize(657, 574)
        GraphsWindow.setStyleSheet("QWidget {\n"
"  background-color: #fff;\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 10px 10px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 1px solid #9ac3fe;\n"
"}\n"
"QMenu {\n"
"background-color: #fff;\n"
"border: 1px solid black;\n"
"margin: 2px;\n"
"}\n"
"QMenu::item {\n"
"background-color: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"background-color: #0b5ed7;\n"
"color: rgb(255,255,255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(GraphsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_get_graphs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_graphs.setGeometry(QtCore.QRect(420, 452, 171, 51))
        self.pushButton_get_graphs.setObjectName("pushButton_get_graphs")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(50, 50, 500, 400))
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        GraphsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GraphsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 21))
        self.menubar.setObjectName("menubar")
        GraphsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GraphsWindow)
        self.statusbar.setObjectName("statusbar")
        GraphsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GraphsWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphsWindow)

    def retranslateUi(self, GraphsWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphsWindow.setWindowTitle(_translate("GraphsWindow", "GraphsWindow"))
        self.pushButton_get_graphs.setText(_translate("GraphsWindow", "Obtener Imagenes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphsWindow = QtWidgets.QMainWindow()
    ui = Ui_GraphsWindow()
    ui.setupUi(GraphsWindow)
    GraphsWindow.show()
    sys.exit(app.exec_())
